apiVersion: batch/v1
kind: Job
metadata:
  name: nilay-formalize
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                       #- NVIDIA-A100-SXM4-80GB
                       #- NVIDIA-A100-80GB-PCIe
                       #- NVIDIA-A100-80GB-PCIe
                      - NVIDIA-GeForce-RTX-4090
                        # - key: nvidia.com/cuda.driver.major
                        #   operator: In
                        #   values: ["525", "530", "535"]
      containers:
        - name: train
          image: "ghcr.io/offendo/formalize:latest"
          command: ["bash", "run.sh"]
          workingDir: /app/formalize
          volumeMounts:
            - name: git-repo
              mountPath: /app
            - name: nilay-data-volume-rwm
              mountPath: /volume
            - name: api-tokens
              mountPath: /etc/api-tokens
          resources:
            limits:
              memory: 64Gi
              cpu: 4
              nvidia.com/gpu: "4"
              ephemeral-storage: 100Gi
            requests:
              memory: 64Gi
              cpu: 4
              nvidia.com/gpu: "4"
              ephemeral-storage: 100Gi
        - name: chmod
          image: alpine:latest
          command: ["chmod", "-R", "a+rw", "/volume/formal-align"]
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: nilay-data-volume-rwm
              mountPath: /volume
      securityContext:
        fsGroup: 101
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: nilay-data-volume-rwm
          persistentVolumeClaim:
            claimName: nilay-data-volume-rwm
        - name: git-secret
          secret:
            defaultMode: 0400
            secretName: nilay-git-creds
        - name: api-tokens
          secret:
            defaultMode: 0400
            secretName: nilay-api-tokens
      restartPolicy: Never
  backoffLimit: 0
