apiVersion: v1
kind: Pod
metadata:
  name: nilay-formalize-test-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
                  - NVIDIA-GeForce-RTX-4090
                  - NVIDIA-A100-SXM4-80GB
                  - NVIDIA-A100-80GB-PCIe
                  - NVIDIA-A100-PCIE-40GB
  imagePullSecrets:
    - name: nilay-ghcr-key
  containers:
    - name: train
      image: ghcr.io/offendo/formalize:latest
      command: ["sleep", "infinity"]
      workingDir: /app/formalize
      env:
        - name: MODEL_NAME
          value: "meta-llama/Llama-3.2-3B"
        - name: WANDB_RUN
          value: "debug"
        - name: LR
          value: "2e-5"
        - name: OPTIMIZER
          value: "paged_adamw_8bit"
        - name: SCHEDULER
          value: "cosine"
        - name: EPOCHS
          value: "2"
        - name: BATCH_SIZE
          value: "4"
        - name: GRAD_ACC
          value: "4"
        - name: EVAL_STEPS
          value: "500"
        - name: GRAD_CKPT
          value: ""
        - name: LORA_RANK
          value: "-1"
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: git-repo
          mountPath: /app
        - name: nilay-data-volume-rwm
          mountPath: /volume
        - name: api-tokens
          mountPath: /etc/api-tokens
      resources:
        limits:
          memory: 128Gi
          cpu: 2
          nvidia.com/gpu: "2"
        requests:
          memory: 128Gi
          cpu: 2
          nvidia.com/gpu: "2"
  initContainers:
    - name: git-sync
      image: registry.k8s.io/git-sync/git-sync:v4.1.0
      args:
        - "--repo=git@github.com:offendo/formalize"
        - "--depth=1"
        - "--one-time"
        - "--root=/git"
      volumeMounts:
        - name: git-repo
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
    - name: chmod
      image: alpine:latest
      command: ["chmod", "-R", "a+rw", "/volume"]
      volumeMounts:
        - name: nilay-data-volume-rwm
          mountPath: /volume
  securityContext:
    fsGroup: 101
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: git-repo
      emptyDir: {}
    - name: nilay-data-volume-rwm
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm
    - name: git-secret
      secret:
        defaultMode: 0400
        secretName: nilay-git-creds
    - name: api-tokens
      secret:
        defaultMode: 0400
        secretName: nilay-api-tokens
  restartPolicy: Never

