apiVersion: v1
kind: Pod
metadata:
  name: nilay-verifier-pod
spec:
  imagePullSecrets:
    - name: nilay-ghcr-key
  containers:
    - name: verifier
      image: projectnumina/kimina-lean-server:1.0.0
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: nilay-data-volume-rwm
          mountPath: /volume
        - name: api-tokens
          mountPath: /etc/api-tokens
      resources:
        limits:
          memory: 32Gi
          cpu: 4
        requests:
          memory: 32Gi
          cpu: 4
  securityContext:
    fsGroup: 101
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: nilay-data-volume-rwm
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm
    - name: api-tokens
      secret:
        defaultMode: 0400
        secretName: nilay-api-tokens
  restartPolicy: Never

