apiVersion: batch/v1
kind: Job
metadata:
  name: nilay-formalize-verify
spec:
  template:
    spec:
      imagePullSecrets:
        - name: nilay-ghcr-key
      shareProcessNamespace: true
      containers:
        - name: train
          image: ghcr.io/offendo/formalize:latest
          command: ["bash", "run_pipeline.sh"]
          workingDir: /app/formalize
          env:
            - name: SKIP_TRAIN
              value: "true"
            - name: SKIP_INFERENCE
              value: "true"
            - name: SKIP_SCORE
              value: "true"
            - name: VERIFY_INPUT
              value: /volume/autoformalization/full_herald_iter3_positives_output.json
            - name: VERIFY_OUTPUT
              value: /volume/autoformalization/full_herald_iter3_positives_verified.json
            - name: VERIFY_NUM_SAMPLES
              value: "1024"
          volumeMounts:
            - name: git-repo
              mountPath: /app
            - name: nilay-data-volume-rwm
              mountPath: /volume
            - name: api-tokens
              mountPath: /etc/api-tokens
            - name: dshm
              mountPath: /dev/shm
          resources:
            limits:
              memory: 32Gi
              cpu: 2
              ephemeral-storage: 30Gi
            requests:
              memory: 32Gi
              cpu: 2
              ephemeral-storage: 30Gi
        - name: verifier
          image: projectnumina/kimina-lean-server:1.0.0
          readinessProbe:
            httpGet:
              path: /health
              port: 12332
            initialDelaySeconds: 5
          env:
            - name: "LEANSERVER_MAX_REPLS"
              value: "10"
            - name: "LEANSERVER_MAX_CONCURRENT_REQUESTS"
              value: "32"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: nilay-data-volume-rwm
              mountPath: /volume
            - name: api-tokens
              mountPath: /etc/api-tokens
          resources:
            limits:
              memory: 128Gi
              cpu: 10
            requests:
              memory: 128Gi
              cpu: 10
      initContainers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.1.0
          args:
            - "--repo=git@github.com:offendo/formalize"
            - "--depth=1"
            - "--one-time"
            - "--root=/git"
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: git-repo
              mountPath: /git
            - name: git-secret
              mountPath: /etc/git-secret
        - name: chmod
          image: alpine:latest
          command: ["chmod", "a+rw", "/volume/"]
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: nilay-data-volume-rwm
              mountPath: /volume
      securityContext:
        fsGroup: 101
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: nilay-data-volume-rwm
          persistentVolumeClaim:
            claimName: nilay-data-volume-rwm
        - name: git-secret
          secret:
            defaultMode: 0400
            secretName: nilay-git-creds
        - name: api-tokens
          secret:
            defaultMode: 0400
            secretName: nilay-api-tokens
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
  backoffLimit: 0
