apiVersion: batch/v1
kind: Job
metadata:
  name: nilay-formalize-run-herald-full
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-3090
                      - NVIDIA-GeForce-RTX-4090
                      - NVIDIA-A100-SXM4-80GB
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-A40
                        # - key: nvidia.com/cuda.driver.major
                        #   operator: In
                        #   values: ["525", "530", "535"]
      imagePullSecrets:
        - name: nilay-ghcr-key
      containers:
        - name: train
          image: ghcr.io/offendo/formalize:latest
          command: ["bash", "scripts/run_herald.sh"]
          workingDir: /app/formalize
          env:
            - name: MODEL
              value: /volume/herald_iteration_1/merged
            - name: DATASET
              value: offendo/math-atlas-titled-theorems
            - name: OUTPUT_PATH
              value: /volume/math_atlas_herald_iteration_2_formatted
            - name: NUM_SAMPLES
              value: "-1"
          volumeMounts:
            - name: git-repo
              mountPath: /app
            - name: nilay-data-volume-rwm
              mountPath: /volume
            - name: api-tokens
              mountPath: /etc/api-tokens
            - name: dshm
              mountPath: /dev/shm
          resources:
            limits:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: "2"
            requests:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: "2"
      initContainers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.1.0
          args:
            - "--repo=git@github.com:offendo/formalize"
            - "--depth=1"
            - "--one-time"
            - "--root=/git"
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: git-repo
              mountPath: /git
            - name: git-secret
              mountPath: /etc/git-secret
        - name: chmod
          image: alpine:latest
          command: ["chmod", "a+rw", "/volume/"]
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: nilay-data-volume-rwm
              mountPath: /volume
      securityContext:
        fsGroup: 101
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: nilay-data-volume-rwm
          persistentVolumeClaim:
            claimName: nilay-data-volume-rwm
        - name: git-secret
          secret:
            defaultMode: 0400
            secretName: nilay-git-creds
        - name: api-tokens
          secret:
            defaultMode: 0400
            secretName: nilay-api-tokens
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
  backoffLimit: 0
